name: heartpocket
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8533990341238678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3a3b'
    - '#fbe1d4'
    - '#1f160d'
    - '#636469'
    - '#9e979e'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
